### ISSUE TITLE
upload pictures

### ISSUE THREAD

**Issue by Carinalo93** [Carinalo93/LiteSolder#1]
![prgstart](https://user-images.githubusercontent.com/44228694/52345047-95ab6780-2a1c-11e9-8947-3c57b1a6f098.PNG)
![prglitesolder](https://user-images.githubusercontent.com/44228694/52345048-97752b00-2a1c-11e9-98a4-518c0cd685bf.PNG)

**Comment by Carinalo93** [comment]
![litesolder](https://user-images.githubusercontent.com/44228694/52347222-b629f080-2a21-11e9-8768-c68ef8ff4792.png)

**Comment by Carinalo93** [comment]
![img_0272](https://user-images.githubusercontent.com/44228694/52430895-67568680-2b07-11e9-9bde-620391de156c.JPG)

![mechswitchpcb](https://user-images.githubusercontent.com/44228694/52430897-69204a00-2b07-11e9-8a30-cbc1aadfa679.JPG)

**Comment by Carinalo93** [comment]
![switching point](https://user-images.githubusercontent.com/44228694/52581386-e9f28500-2e2a-11e9-82a1-55e79beedcc6.png)

**Comment by Carinalo93** [comment]
![calibrate nozzle](https://user-images.githubusercontent.com/44228694/52587186-cbe05100-2e39-11e9-9767-02f6d7ae6ec6.png)

**Comment by Carinalo93** [comment]
![einstellungen kameraerkennung nozzle](https://user-images.githubusercontent.com/44228694/52589011-1bc11700-2e3e-11e9-9c83-17dc011eb43a.jpg)

**Comment by Carinalo93** [comment]
![fiducials](https://user-images.githubusercontent.com/44228694/52590066-af93e280-2e40-11e9-908e-a89c6c96b951.png)

**Comment by Carinalo93** [comment]
![litesoldersw](https://user-images.githubusercontent.com/44228694/52661079-75d6e080-2f01-11e9-9dfa-1ebb6ae7c87c.png)

**Comment by Carinalo93** [comment]
![einstellungen kameraerkennung nozzle](https://user-images.githubusercontent.com/44228694/52663190-5bebcc80-2f06-11e9-8987-cd326e036c30.png)

**Comment by Carinalo93** [comment]
![solderpaste](https://user-images.githubusercontent.com/44228694/52745219-d25bfd80-2fde-11e9-85b8-75c1818c1120.jpg)

**Comment by techscout1** [comment]
![step 2](https://user-images.githubusercontent.com/25740406/52914768-9a99d200-32cc-11e9-83df-2510180e5949.png)
![view2](https://user-images.githubusercontent.com/25740406/52914770-9f5e8600-32cc-11e9-89a5-c01379d55d0a.png)
![view3](https://user-images.githubusercontent.com/25740406/52914775-a2597680-32cc-11e9-9623-0a003eee91dd.png)
![dispenser](https://user-images.githubusercontent.com/25740406/52914777-a4bbd080-32cc-11e9-8f44-75a9d8a1ef98.png)
![Uploading View1.png…]()
![Uploading View2.png…]()

**Comment by techscout1** [comment]
![prasi2](https://user-images.githubusercontent.com/25740406/52914902-10526d80-32ce-11e9-9ff3-42f7ec2e7a1e.png)
![step 2](https://user-images.githubusercontent.com/25740406/52914903-10eb0400-32ce-11e9-85e1-1658b9fa768b.png)

![view1](https://user-images.githubusercontent.com/25740406/52914904-10eb0400-32ce-11e9-879c-172a7d843f37.png)
![view2](https://user-images.githubusercontent.com/25740406/52914905-10eb0400-32ce-11e9-8dae-44ca79a4eacb.png)
![view3](https://user-images.githubusercontent.com/25740406/52914906-10eb0400-32ce-11e9-9fdd-5a515c50861e.png)
![dispenser](https://user-images.githubusercontent.com/25740406/52914907-10eb0400-32ce-11e9-967c-f47b6efffade.png)

**Comment by Carinalo93** [comment]
![lotpasten](https://user-images.githubusercontent.com/44228694/52916662-af816000-32e2-11e9-97d6-f06e17f9bf7a.jpg)
![vergleich lotpasten unverlotet](https://user-images.githubusercontent.com/44228694/52916793-2c610980-32e4-11e9-8659-7d21f1b2b804.png)
![vergleich lotpasten verlotet](https://user-images.githubusercontent.com/44228694/52916796-2ff49080-32e4-11e9-9bed-5f2928b95439.png)
![ergebnis bga 81](https://user-images.githubusercontent.com/44228694/52916799-34b94480-32e4-11e9-8348-f6fc9f721303.png)
