### ISSUE TITLE
LiteSolder Installation

### ISSUE THREAD

**Issue by SENSEI-Matt** [Carinalo93/LiteSolder#4]
Hi,

I'm just building my LitePlacer and have decided to incorporate LiteSolder right from the start. I have a couple of questions regarding placement of components to accommodate the increase in width of the gantry when LiteSolder is added. Firstly increasing the width of the gantry causes the X axis left side limit switch to become ineffective, did you relocate the limit switch to a specific place? Secondly the placement of the up facing camera - do you have a recommended location as the LiteSolder reduces the usable X axis space due again to the increase in gantry size. I know I am being lazy as I could work it out for myself but any guidance would save me time and effort.

Thanks

Matt

**Comment by techscout1** [comment]
Hey Matt,

we solved the X-Axis Problem by creating a new X-Endstop plate which can be easily mount under the main rail. The part is available in our documentation. [Click here](https://github.com/Carinalo93/LiteSolder/wiki/LiteSolder-Parts) Look vor "X-Endstop" <-- With this you can still use the X-Endstop with the bigger gantry.

We didnt use the uplooking camera in our setup. All measurement steps will be done by the down looking camera. Its done by the principle that we print some dots to a measurementplate which is just a bare copper plate. These dots will be measured by the downlooking camera. --> So we cant recommend a place for the up looking camera ;) - At our Liteplacer this camera is mounted near left limit of y-axis in the middle of the workspace.

We hope this will help you. If you have futher question we will help you! :)

greetings

Jan - LiteSolder

**Comment by SENSEI-Matt** [comment]
Thanks Jan.
